version: '3.8'

services:
  inventoryman-api:
    image: inventoryman-api:latest
    build:
      context: .
      dockerfile: InventoryMan.API/Dockerfile
    ports:
      - "8081:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DATABASE_CONNECTION_STRING=Host=db-inventory-test-do-user-14240857-0.j.db.ondigitalocean.com;Port=25060;Database=db-inventory-test;Username=doadmin;Password=AVNS_k_xfsbtNv5tDnn52YS0
      - PORT=8080

