version: '3.8'

services:
  inventoryman-api:
    image: inventoryman-api:latest
    build:
      context: .
      dockerfile: InventoryMan.API/Dockerfile
    ports:
      - "5000:8080"
      - "5001:8443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DATABASE_CONNECTION_STRING=Host=192.168.1.64;Database=inventoryMan;Username=postgres;Password=abc+1234