CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "ProductCategories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    CONSTRAINT "PK_ProductCategories" PRIMARY KEY ("Id")
);

CREATE TABLE "Stores" (
    "Id" text NOT NULL,
    "Name" text NOT NULL,
    "Address" text NOT NULL,
    "Phone" text NOT NULL,
    CONSTRAINT "PK_Stores" PRIMARY KEY ("Id")
);

CREATE TABLE "Test" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Data" text NOT NULL,
    CONSTRAINT "PK_Test" PRIMARY KEY ("Id")
);

CREATE TABLE "Products" (
    "Id" text NOT NULL,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    "CategoryId" integer NOT NULL,
    "Price" numeric(18,2) NOT NULL,
    "Sku" text NOT NULL,
    CONSTRAINT "PK_Products" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Products_ProductCategories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "ProductCategories" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Inventories" (
    "Id" text NOT NULL,
    "ProductId" text NOT NULL,
    "StoreId" text NOT NULL,
    "Quantity" integer NOT NULL,
    "MinStock" integer NOT NULL,
    CONSTRAINT "PK_Inventories" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Inventories_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Inventories_Stores_StoreId" FOREIGN KEY ("StoreId") REFERENCES "Stores" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Movements" (
    "Id" text NOT NULL,
    "ProductId" text NOT NULL,
    "SourceStoreId" text,
    "TargetStoreId" text,
    "Quantity" integer NOT NULL,
    "Timestamp" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "Type" integer NOT NULL,
    CONSTRAINT "PK_Movements" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Movements_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
);

INSERT INTO "Test" ("Id", "Data")
VALUES (1, 'Database connection successfully established');


CREATE UNIQUE INDEX "IX_Inventories_ProductId_StoreId" ON "Inventories" ("ProductId", "StoreId");

CREATE INDEX "IX_Inventories_StoreId" ON "Inventories" ("StoreId");

CREATE INDEX "IX_Movements_ProductId" ON "Movements" ("ProductId");

CREATE INDEX "IX_Products_CategoryId" ON "Products" ("CategoryId");

CREATE UNIQUE INDEX "IX_Products_Sku" ON "Products" ("Sku");

SELECT setval(
    pg_get_serial_sequence('"ProductCategories"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "ProductCategories") + 1,
        nextval(pg_get_serial_sequence('"ProductCategories"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"Test"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Test") + 1,
        nextval(pg_get_serial_sequence('"Test"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250104154409_InitialCreate', '8.0.0');

COMMIT;

