// <auto-generated />
using System;
using InventoryMan.Infrastructure.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InventoryMan.Infrastructure.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20250103180331_TestData")]
    partial class TestData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InventoryMan.Core.Entities.Inventory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("MinStock")
                        .HasColumnType("integer");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("StoreId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.HasIndex("ProductId", "StoreId")
                        .IsUnique();

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("InventoryMan.Core.Entities.Movement", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("SourceStoreId")
                        .HasColumnType("text");

                    b.Property<string>("TargetStoreId")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Movements");
                });

            modelBuilder.Entity("InventoryMan.Core.Entities.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = "18b43125-e3f2-435a-98f5-d70314cc8824",
                            CategoryId = 1,
                            Description = "Producto electrónico versátil",
                            Name = "Smartphone X1",
                            Price = 299.99m,
                            Sku = "SMRT001"
                        },
                        new
                        {
                            Id = "2948aa32-2d99-4467-8b22-b7f70d7d5a3d",
                            CategoryId = 2,
                            Description = "Accesorio deportivo premium",
                            Name = "Reloj Deportivo Pro",
                            Price = 149.99m,
                            Sku = "SPRT002"
                        },
                        new
                        {
                            Id = "12c26367-a9bc-455a-8ad5-46038efdc3c1",
                            CategoryId = 1,
                            Description = "Audio de alta calidad",
                            Name = "Auriculares Wireless",
                            Price = 89.99m,
                            Sku = "AUDIO003"
                        },
                        new
                        {
                            Id = "5577fc34-8608-44db-abdc-432426c06e0f",
                            CategoryId = 2,
                            Description = "Equipo fitness resistente",
                            Name = "Pesas Ajustables",
                            Price = 199.99m,
                            Sku = "FIT004"
                        },
                        new
                        {
                            Id = "4d67070b-5220-4a1e-92a8-abb328eac800",
                            CategoryId = 1,
                            Description = "Tablet última generación",
                            Name = "Tablet Pro 10",
                            Price = 399.99m,
                            Sku = "TAB005"
                        },
                        new
                        {
                            Id = "184e50f8-3d45-485e-aeb3-aee805190e29",
                            CategoryId = 2,
                            Description = "Equipamiento deportivo",
                            Name = "Balón Profesional",
                            Price = 29.99m,
                            Sku = "BALL006"
                        },
                        new
                        {
                            Id = "0f212a19-f315-4efd-b493-9b73df643eac",
                            CategoryId = 1,
                            Description = "Cámara compacta HD",
                            Name = "Cámara Digital X20",
                            Price = 249.99m,
                            Sku = "CAM007"
                        },
                        new
                        {
                            Id = "151bf193-cdc0-47f6-8ff8-5788b4620165",
                            CategoryId = 2,
                            Description = "Ropa deportiva premium",
                            Name = "Camiseta Tech-Fit",
                            Price = 34.99m,
                            Sku = "WEAR008"
                        },
                        new
                        {
                            Id = "ca128b8a-56ee-4c18-b90a-8dee3369d739",
                            CategoryId = 1,
                            Description = "Altavoz potente",
                            Name = "Speaker Bluetooth",
                            Price = 79.99m,
                            Sku = "SPK009"
                        },
                        new
                        {
                            Id = "e09e47ee-2f89-4fc3-88fa-2a973febf7fe",
                            CategoryId = 2,
                            Description = "Calzado deportivo",
                            Name = "Zapatillas Pro-Run",
                            Price = 89.99m,
                            Sku = "SHOE010"
                        },
                        new
                        {
                            Id = "f878551b-9891-4069-87f6-c0d445ebff88",
                            CategoryId = 1,
                            Description = "Smartwatch avanzado",
                            Name = "Reloj Smart V2",
                            Price = 199.99m,
                            Sku = "WATCH011"
                        },
                        new
                        {
                            Id = "6810911c-2e51-477b-83f8-5541297de642",
                            CategoryId = 2,
                            Description = "Equipo de entrenamiento",
                            Name = "Banda Elástica Pro",
                            Price = 19.99m,
                            Sku = "BAND012"
                        },
                        new
                        {
                            Id = "1fcde78f-fd06-42fb-bb7d-5b0395d03b6f",
                            CategoryId = 1,
                            Description = "Teclado gaming",
                            Name = "Teclado RGB Pro",
                            Price = 129.99m,
                            Sku = "KEY013"
                        },
                        new
                        {
                            Id = "5fc6a088-85f3-4be4-a7c2-c5c603e55e6e",
                            CategoryId = 2,
                            Description = "Accesorio yoga",
                            Name = "Mat Premium",
                            Price = 39.99m,
                            Sku = "YOGA014"
                        },
                        new
                        {
                            Id = "deea439b-83ad-48d4-9365-d2ca2bb7e5b8",
                            CategoryId = 1,
                            Description = "Mouse gaming",
                            Name = "Mouse Gamer X",
                            Price = 59.99m,
                            Sku = "MOUSE015"
                        },
                        new
                        {
                            Id = "fe9d4b2f-8cf4-4fab-90ba-4788bc01de4b",
                            CategoryId = 2,
                            Description = "Botella deportiva",
                            Name = "Botella Térmica",
                            Price = 24.99m,
                            Sku = "BTL016"
                        },
                        new
                        {
                            Id = "566b8350-1fad-4c11-878a-538bae7ab7ab",
                            CategoryId = 1,
                            Description = "Webcam HD",
                            Name = "Webcam Pro 4K",
                            Price = 89.99m,
                            Sku = "CAM017"
                        },
                        new
                        {
                            Id = "125ec9c0-b5f4-41fd-8c1b-fba65e5b2443",
                            CategoryId = 2,
                            Description = "Mochila deportiva",
                            Name = "Mochila Sport Pro",
                            Price = 44.99m,
                            Sku = "BAG018"
                        },
                        new
                        {
                            Id = "f6630ff2-6a6f-4e21-b5e2-95d69eeafab2",
                            CategoryId = 1,
                            Description = "Batería portátil",
                            Name = "PowerBank 20000",
                            Price = 49.99m,
                            Sku = "PWR019"
                        },
                        new
                        {
                            Id = "2c1750e0-bcea-4187-8efc-83ad14691229",
                            CategoryId = 2,
                            Description = "Guantes fitness",
                            Name = "Guantes Pro-Lift",
                            Price = 29.99m,
                            Sku = "GLV020"
                        },
                        new
                        {
                            Id = "57293dc2-bbfc-4d09-b936-c3d7691e244e",
                            CategoryId = 1,
                            Description = "Hub USB",
                            Name = "USB Hub 4-Port",
                            Price = 29.99m,
                            Sku = "USB021"
                        },
                        new
                        {
                            Id = "46f4a4b2-c4f9-46c2-ae30-597ce8796fa4",
                            CategoryId = 2,
                            Description = "Toalla deportiva",
                            Name = "Toalla Microfibra",
                            Price = 14.99m,
                            Sku = "TWL022"
                        },
                        new
                        {
                            Id = "85b4eb61-a623-4018-bc60-7357f37f6af4",
                            CategoryId = 1,
                            Description = "Soporte laptop",
                            Name = "Soporte Ergonómico",
                            Price = 39.99m,
                            Sku = "STND023"
                        },
                        new
                        {
                            Id = "c318f00d-9c53-4116-bf01-f1c38b0e7cd0",
                            CategoryId = 2,
                            Description = "Bolsa deporte",
                            Name = "Bolsa Gym Pro",
                            Price = 34.99m,
                            Sku = "GYM024"
                        },
                        new
                        {
                            Id = "f3e640f6-0ade-4f44-972c-0df63517e3a4",
                            CategoryId = 1,
                            Description = "Cable HDMI",
                            Name = "HDMI Premium 2m",
                            Price = 19.99m,
                            Sku = "HDMI025"
                        },
                        new
                        {
                            Id = "2e5fac31-502b-4763-a729-94ec14b61102",
                            CategoryId = 2,
                            Description = "Banda cardio",
                            Name = "Monitor Cardíaco",
                            Price = 49.99m,
                            Sku = "HRT026"
                        },
                        new
                        {
                            Id = "2c45b97d-5e21-42b0-a1fb-99c8cc49329f",
                            CategoryId = 1,
                            Description = "Funda tablet",
                            Name = "Funda Protectora",
                            Price = 24.99m,
                            Sku = "CASE027"
                        },
                        new
                        {
                            Id = "6a213881-23f6-44aa-963e-f29087c4991a",
                            CategoryId = 2,
                            Description = "Rodilleras pro",
                            Name = "Rodilleras Sport",
                            Price = 19.99m,
                            Sku = "KNEE028"
                        },
                        new
                        {
                            Id = "df38189a-afdb-4319-bf6b-fa8674c4abe8",
                            CategoryId = 1,
                            Description = "Adaptador wifi",
                            Name = "WiFi Adapter Pro",
                            Price = 29.99m,
                            Sku = "WIFI029"
                        },
                        new
                        {
                            Id = "40935125-3491-43cb-b503-bbffe2598235",
                            CategoryId = 2,
                            Description = "Cuerda saltar",
                            Name = "Cuerda Pro-Jump",
                            Price = 14.99m,
                            Sku = "JUMP030"
                        },
                        new
                        {
                            Id = "5e40098d-0431-4952-9dc3-0a6d473bd821",
                            CategoryId = 1,
                            Description = "Luz LED USB",
                            Name = "LED Light Strip",
                            Price = 19.99m,
                            Sku = "LED031"
                        },
                        new
                        {
                            Id = "88ebaff6-0840-46ec-b5da-48b5fedef93c",
                            CategoryId = 2,
                            Description = "Banda cabeza",
                            Name = "Banda Deportiva",
                            Price = 9.99m,
                            Sku = "HEAD032"
                        },
                        new
                        {
                            Id = "4835998d-e90c-4b6e-9335-844b33d9dd51",
                            CategoryId = 1,
                            Description = "Protector pantalla",
                            Name = "Screen Guard Pro",
                            Price = 14.99m,
                            Sku = "SCRN033"
                        },
                        new
                        {
                            Id = "86390ab3-a16c-4af8-9d6b-7d9c50f0a8d5",
                            CategoryId = 2,
                            Description = "Botella shake",
                            Name = "Shaker Pro",
                            Price = 16.99m,
                            Sku = "SHAKE034"
                        },
                        new
                        {
                            Id = "a4874a2e-3733-4982-a8eb-7c9627b96b21",
                            CategoryId = 1,
                            Description = "Soporte móvil",
                            Name = "Phone Stand",
                            Price = 15.99m,
                            Sku = "STND035"
                        },
                        new
                        {
                            Id = "2edf0187-d7e0-4825-a65b-72397a22822c",
                            CategoryId = 2,
                            Description = "Muñequeras",
                            Name = "Wrist Support",
                            Price = 12.99m,
                            Sku = "WRST036"
                        },
                        new
                        {
                            Id = "84a7f1ca-5aac-4f59-811a-2851f98a663a",
                            CategoryId = 1,
                            Description = "Limpiador pantalla",
                            Name = "Screen Cleaner",
                            Price = 9.99m,
                            Sku = "CLN037"
                        },
                        new
                        {
                            Id = "703ac78f-0641-4a2d-be10-9c63be362c5f",
                            CategoryId = 2,
                            Description = "Bolsa zapatos",
                            Name = "Shoe Bag Sport",
                            Price = 11.99m,
                            Sku = "BAG038"
                        },
                        new
                        {
                            Id = "4cdff008-2166-4855-adce-f39e50bbac3f",
                            CategoryId = 1,
                            Description = "Organizador cables",
                            Name = "Cable Manager",
                            Price = 8.99m,
                            Sku = "ORG039"
                        },
                        new
                        {
                            Id = "da749843-17aa-45c5-a753-1e39f91d4e93",
                            CategoryId = 2,
                            Description = "Toalla pequeña",
                            Name = "Mini Towel",
                            Price = 7.99m,
                            Sku = "TWL040"
                        },
                        new
                        {
                            Id = "0604728a-7c6b-4e54-96a6-7f6d313b51b8",
                            CategoryId = 1,
                            Description = "Protector cable",
                            Name = "Cable Protector",
                            Price = 6.99m,
                            Sku = "PROT041"
                        },
                        new
                        {
                            Id = "b03c3212-e211-4089-ac1b-8a281bb67ca1",
                            CategoryId = 2,
                            Description = "Banda medición",
                            Name = "Measure Tape",
                            Price = 8.99m,
                            Sku = "MEAS042"
                        },
                        new
                        {
                            Id = "dd839a53-1ba8-43b4-b89b-0252d8bb693f",
                            CategoryId = 1,
                            Description = "Mini ventilador",
                            Name = "USB Fan",
                            Price = 12.99m,
                            Sku = "FAN043"
                        },
                        new
                        {
                            Id = "803915d2-59bb-44ec-938f-577a31bf43b4",
                            CategoryId = 2,
                            Description = "Candado gym",
                            Name = "Gym Lock",
                            Price = 9.99m,
                            Sku = "LOCK044"
                        },
                        new
                        {
                            Id = "adc225dc-8a42-4e20-b8f0-736ec3316684",
                            CategoryId = 1,
                            Description = "Almohadilla mouse",
                            Name = "Mouse Pad Pro",
                            Price = 11.99m,
                            Sku = "PAD045"
                        },
                        new
                        {
                            Id = "54b04dc7-6366-4034-bea1-23027aa97c51",
                            CategoryId = 2,
                            Description = "Banda resistencia",
                            Name = "Resistance Band",
                            Price = 13.99m,
                            Sku = "BAND046"
                        },
                        new
                        {
                            Id = "8a535eb1-67e8-4176-b6a5-9dcbab3c5e80",
                            CategoryId = 1,
                            Description = "Soporte tablet",
                            Name = "Tablet Mount",
                            Price = 16.99m,
                            Sku = "MNT047"
                        },
                        new
                        {
                            Id = "f1cd8513-a17a-4b66-95bb-38127115f6ec",
                            CategoryId = 2,
                            Description = "Bolsa agua",
                            Name = "Water Bag",
                            Price = 15.99m,
                            Sku = "H2O048"
                        },
                        new
                        {
                            Id = "a2edda5b-01e9-490b-bf97-2957fe7eb6f8",
                            CategoryId = 1,
                            Description = "Hub cargador",
                            Name = "Charging Hub",
                            Price = 24.99m,
                            Sku = "CHRG049"
                        },
                        new
                        {
                            Id = "2b0dd133-c751-46f2-a678-8d5513bac9eb",
                            CategoryId = 2,
                            Description = "Timer digital",
                            Name = "Sport Timer",
                            Price = 18.99m,
                            Sku = "TIME050"
                        });
                });

            modelBuilder.Entity("InventoryMan.Core.Entities.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electrónicos y accesorios tecnológicos"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Deportivos y fitness"
                        });
                });

            modelBuilder.Entity("InventoryMan.Core.Entities.Store", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Stores");

                    b.HasData(
                        new
                        {
                            Id = "859251b6-f0fc-480d-87f2-edd3de9bc817",
                            Address = "Address 1",
                            Name = "Store 1",
                            Phone = "123456789"
                        },
                        new
                        {
                            Id = "5f7b74c4-1ff7-4c7e-b54d-54f3d382b7d1",
                            Address = "Address 2",
                            Name = "Store 2",
                            Phone = "987654321"
                        });
                });

            modelBuilder.Entity("InventoryMan.Core.Entities.Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Test");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Data = "Access to DB it's working"
                        });
                });

            modelBuilder.Entity("InventoryMan.Core.Entities.Inventory", b =>
                {
                    b.HasOne("InventoryMan.Core.Entities.Product", "Product")
                        .WithMany("Inventories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventoryMan.Core.Entities.Store", "Store")
                        .WithMany("Inventories")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("InventoryMan.Core.Entities.Movement", b =>
                {
                    b.HasOne("InventoryMan.Core.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("InventoryMan.Core.Entities.Product", b =>
                {
                    b.HasOne("InventoryMan.Core.Entities.ProductCategory", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("InventoryMan.Core.Entities.Product", b =>
                {
                    b.Navigation("Inventories");
                });

            modelBuilder.Entity("InventoryMan.Core.Entities.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("InventoryMan.Core.Entities.Store", b =>
                {
                    b.Navigation("Inventories");
                });
#pragma warning restore 612, 618
        }
    }
}
