// <auto-generated />
using System;
using InventoryMan.Infrastructure.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InventoryMan.Infrastructure.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20250102032523_MakeSourceStoreIdNullable")]
    partial class MakeSourceStoreIdNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InventoryMan.Core.Entities.Inventory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("MinStock")
                        .HasColumnType("integer");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductId1")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("StoreId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProductId1");

                    b.HasIndex("StoreId");

                    b.HasIndex("ProductId", "StoreId")
                        .IsUnique();

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("InventoryMan.Core.Entities.Movement", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("SourceStoreId")
                        .HasColumnType("text");

                    b.Property<string>("TargetStoreId")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Movements");
                });

            modelBuilder.Entity("InventoryMan.Core.Entities.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = "0d6c0b1c-8ec5-43f9-ab79-cb1cb07a4633",
                            CategoryId = 1,
                            Description = "Producto electrónico versátil",
                            Name = "Smartphone X1",
                            Price = 299.99m,
                            Sku = "SMRT001"
                        },
                        new
                        {
                            Id = "e437797b-a50d-49b7-ac30-dbafc9de7b00",
                            CategoryId = 2,
                            Description = "Accesorio deportivo premium",
                            Name = "Reloj Deportivo Pro",
                            Price = 149.99m,
                            Sku = "SPRT002"
                        },
                        new
                        {
                            Id = "fbf15bde-4f87-4de3-bcc9-77f6926c6fb7",
                            CategoryId = 1,
                            Description = "Audio de alta calidad",
                            Name = "Auriculares Wireless",
                            Price = 89.99m,
                            Sku = "AUDIO003"
                        },
                        new
                        {
                            Id = "6e740613-898c-4ad0-bd36-5c4d7da06355",
                            CategoryId = 2,
                            Description = "Equipo fitness resistente",
                            Name = "Pesas Ajustables",
                            Price = 199.99m,
                            Sku = "FIT004"
                        },
                        new
                        {
                            Id = "38d7f3e0-eaa4-4c84-b681-9b998d89a3f2",
                            CategoryId = 1,
                            Description = "Tablet última generación",
                            Name = "Tablet Pro 10",
                            Price = 399.99m,
                            Sku = "TAB005"
                        },
                        new
                        {
                            Id = "2f4a4232-03fb-4567-a2aa-a8f14ea855c0",
                            CategoryId = 2,
                            Description = "Equipamiento deportivo",
                            Name = "Balón Profesional",
                            Price = 29.99m,
                            Sku = "BALL006"
                        },
                        new
                        {
                            Id = "313cef05-2dbc-49e5-a4a9-12634e690ea9",
                            CategoryId = 1,
                            Description = "Cámara compacta HD",
                            Name = "Cámara Digital X20",
                            Price = 249.99m,
                            Sku = "CAM007"
                        },
                        new
                        {
                            Id = "d10cd842-4701-4740-8360-9798aff0bc02",
                            CategoryId = 2,
                            Description = "Ropa deportiva premium",
                            Name = "Camiseta Tech-Fit",
                            Price = 34.99m,
                            Sku = "WEAR008"
                        },
                        new
                        {
                            Id = "54dcb400-f938-49e9-bfe9-6333223ee0e3",
                            CategoryId = 1,
                            Description = "Altavoz potente",
                            Name = "Speaker Bluetooth",
                            Price = 79.99m,
                            Sku = "SPK009"
                        },
                        new
                        {
                            Id = "d5550587-53dd-40a3-b9e4-cec7e025cf49",
                            CategoryId = 2,
                            Description = "Calzado deportivo",
                            Name = "Zapatillas Pro-Run",
                            Price = 89.99m,
                            Sku = "SHOE010"
                        },
                        new
                        {
                            Id = "fe27957f-1b98-4511-a4e2-562ecaa934ba",
                            CategoryId = 1,
                            Description = "Smartwatch avanzado",
                            Name = "Reloj Smart V2",
                            Price = 199.99m,
                            Sku = "WATCH011"
                        },
                        new
                        {
                            Id = "d7dca7fc-752f-4cf6-b21b-a95019043f4d",
                            CategoryId = 2,
                            Description = "Equipo de entrenamiento",
                            Name = "Banda Elástica Pro",
                            Price = 19.99m,
                            Sku = "BAND012"
                        },
                        new
                        {
                            Id = "7f689459-9ec4-44aa-bb3b-e1d51964bba3",
                            CategoryId = 1,
                            Description = "Teclado gaming",
                            Name = "Teclado RGB Pro",
                            Price = 129.99m,
                            Sku = "KEY013"
                        },
                        new
                        {
                            Id = "69ec9f3e-10b6-4f82-8b7c-cbcea99efa6b",
                            CategoryId = 2,
                            Description = "Accesorio yoga",
                            Name = "Mat Premium",
                            Price = 39.99m,
                            Sku = "YOGA014"
                        },
                        new
                        {
                            Id = "0b7ab78e-e6a6-4213-aa7c-f3acdf300fed",
                            CategoryId = 1,
                            Description = "Mouse gaming",
                            Name = "Mouse Gamer X",
                            Price = 59.99m,
                            Sku = "MOUSE015"
                        },
                        new
                        {
                            Id = "7ef3e963-2282-4a66-b6c0-8a5b7a5985c3",
                            CategoryId = 2,
                            Description = "Botella deportiva",
                            Name = "Botella Térmica",
                            Price = 24.99m,
                            Sku = "BTL016"
                        },
                        new
                        {
                            Id = "86ae25c6-e87b-4417-bcb0-917fbadf4a56",
                            CategoryId = 1,
                            Description = "Webcam HD",
                            Name = "Webcam Pro 4K",
                            Price = 89.99m,
                            Sku = "CAM017"
                        },
                        new
                        {
                            Id = "f0b43c75-3957-4316-be8e-9da31bea2bf1",
                            CategoryId = 2,
                            Description = "Mochila deportiva",
                            Name = "Mochila Sport Pro",
                            Price = 44.99m,
                            Sku = "BAG018"
                        },
                        new
                        {
                            Id = "53559aa8-c451-4d72-a406-9944dcf5f872",
                            CategoryId = 1,
                            Description = "Batería portátil",
                            Name = "PowerBank 20000",
                            Price = 49.99m,
                            Sku = "PWR019"
                        },
                        new
                        {
                            Id = "9c862fb8-091b-40f7-b797-072b3950f334",
                            CategoryId = 2,
                            Description = "Guantes fitness",
                            Name = "Guantes Pro-Lift",
                            Price = 29.99m,
                            Sku = "GLV020"
                        },
                        new
                        {
                            Id = "aa02b357-ebca-4f5b-a9d6-1d2ced2d28db",
                            CategoryId = 1,
                            Description = "Hub USB",
                            Name = "USB Hub 4-Port",
                            Price = 29.99m,
                            Sku = "USB021"
                        },
                        new
                        {
                            Id = "38185f0d-84b3-410a-b63f-f293f28ea121",
                            CategoryId = 2,
                            Description = "Toalla deportiva",
                            Name = "Toalla Microfibra",
                            Price = 14.99m,
                            Sku = "TWL022"
                        },
                        new
                        {
                            Id = "3dcc00cf-6899-4e7a-958e-12ae7b9d26c6",
                            CategoryId = 1,
                            Description = "Soporte laptop",
                            Name = "Soporte Ergonómico",
                            Price = 39.99m,
                            Sku = "STND023"
                        },
                        new
                        {
                            Id = "47df651e-b686-46bc-8599-bce83f751826",
                            CategoryId = 2,
                            Description = "Bolsa deporte",
                            Name = "Bolsa Gym Pro",
                            Price = 34.99m,
                            Sku = "GYM024"
                        },
                        new
                        {
                            Id = "c95caeae-e7d1-4171-900a-a4e8e9500911",
                            CategoryId = 1,
                            Description = "Cable HDMI",
                            Name = "HDMI Premium 2m",
                            Price = 19.99m,
                            Sku = "HDMI025"
                        },
                        new
                        {
                            Id = "86602d11-26d9-41ae-b99a-e8d1656fec59",
                            CategoryId = 2,
                            Description = "Banda cardio",
                            Name = "Monitor Cardíaco",
                            Price = 49.99m,
                            Sku = "HRT026"
                        },
                        new
                        {
                            Id = "ab1ffcbc-3bc9-4818-93db-0cdc33e15cf9",
                            CategoryId = 1,
                            Description = "Funda tablet",
                            Name = "Funda Protectora",
                            Price = 24.99m,
                            Sku = "CASE027"
                        },
                        new
                        {
                            Id = "592f8943-0cec-404a-ad6c-8d8ad9a1c0c9",
                            CategoryId = 2,
                            Description = "Rodilleras pro",
                            Name = "Rodilleras Sport",
                            Price = 19.99m,
                            Sku = "KNEE028"
                        },
                        new
                        {
                            Id = "9e234d91-48a0-4d8f-8d1a-a5953645aa8c",
                            CategoryId = 1,
                            Description = "Adaptador wifi",
                            Name = "WiFi Adapter Pro",
                            Price = 29.99m,
                            Sku = "WIFI029"
                        },
                        new
                        {
                            Id = "aa2cc449-12b7-4368-a1c0-7e903b34d7b7",
                            CategoryId = 2,
                            Description = "Cuerda saltar",
                            Name = "Cuerda Pro-Jump",
                            Price = 14.99m,
                            Sku = "JUMP030"
                        },
                        new
                        {
                            Id = "eb5664a6-d60e-4bf2-b126-cc03b8cebba4",
                            CategoryId = 1,
                            Description = "Luz LED USB",
                            Name = "LED Light Strip",
                            Price = 19.99m,
                            Sku = "LED031"
                        },
                        new
                        {
                            Id = "5c077915-d11b-4bc2-b457-1cfcd832433b",
                            CategoryId = 2,
                            Description = "Banda cabeza",
                            Name = "Banda Deportiva",
                            Price = 9.99m,
                            Sku = "HEAD032"
                        },
                        new
                        {
                            Id = "d7b6f0a6-85d4-4d4e-9d4b-b53860dc2818",
                            CategoryId = 1,
                            Description = "Protector pantalla",
                            Name = "Screen Guard Pro",
                            Price = 14.99m,
                            Sku = "SCRN033"
                        },
                        new
                        {
                            Id = "e69b8998-591b-4ea8-9ad4-dd10e82b1db8",
                            CategoryId = 2,
                            Description = "Botella shake",
                            Name = "Shaker Pro",
                            Price = 16.99m,
                            Sku = "SHAKE034"
                        },
                        new
                        {
                            Id = "ebc08450-b886-461d-8779-de75e8b6fdcd",
                            CategoryId = 1,
                            Description = "Soporte móvil",
                            Name = "Phone Stand",
                            Price = 15.99m,
                            Sku = "STND035"
                        },
                        new
                        {
                            Id = "eae58d0d-0b01-43a1-9788-20d9a5488582",
                            CategoryId = 2,
                            Description = "Muñequeras",
                            Name = "Wrist Support",
                            Price = 12.99m,
                            Sku = "WRST036"
                        },
                        new
                        {
                            Id = "e51fd9e2-321f-4034-b367-f46caa496d76",
                            CategoryId = 1,
                            Description = "Limpiador pantalla",
                            Name = "Screen Cleaner",
                            Price = 9.99m,
                            Sku = "CLN037"
                        },
                        new
                        {
                            Id = "469b2a7b-5b79-4bf6-94ee-2fc8e78b5693",
                            CategoryId = 2,
                            Description = "Bolsa zapatos",
                            Name = "Shoe Bag Sport",
                            Price = 11.99m,
                            Sku = "BAG038"
                        },
                        new
                        {
                            Id = "fd38c9da-294e-47d1-972e-ccb291cb662f",
                            CategoryId = 1,
                            Description = "Organizador cables",
                            Name = "Cable Manager",
                            Price = 8.99m,
                            Sku = "ORG039"
                        },
                        new
                        {
                            Id = "2df90ae5-ecf4-472e-8160-912085301b6b",
                            CategoryId = 2,
                            Description = "Toalla pequeña",
                            Name = "Mini Towel",
                            Price = 7.99m,
                            Sku = "TWL040"
                        },
                        new
                        {
                            Id = "7e207deb-1b59-4022-bd3a-43c8039ccf26",
                            CategoryId = 1,
                            Description = "Protector cable",
                            Name = "Cable Protector",
                            Price = 6.99m,
                            Sku = "PROT041"
                        },
                        new
                        {
                            Id = "c602d430-c67d-4a53-9e9d-d8abec6dcca4",
                            CategoryId = 2,
                            Description = "Banda medición",
                            Name = "Measure Tape",
                            Price = 8.99m,
                            Sku = "MEAS042"
                        },
                        new
                        {
                            Id = "d22e4664-051a-4311-b94b-6942aaaf058a",
                            CategoryId = 1,
                            Description = "Mini ventilador",
                            Name = "USB Fan",
                            Price = 12.99m,
                            Sku = "FAN043"
                        },
                        new
                        {
                            Id = "7313da1e-0152-4b11-90bc-aeccbc1406f8",
                            CategoryId = 2,
                            Description = "Candado gym",
                            Name = "Gym Lock",
                            Price = 9.99m,
                            Sku = "LOCK044"
                        },
                        new
                        {
                            Id = "f8a2a33d-c329-4f73-a92a-840d84df3124",
                            CategoryId = 1,
                            Description = "Almohadilla mouse",
                            Name = "Mouse Pad Pro",
                            Price = 11.99m,
                            Sku = "PAD045"
                        },
                        new
                        {
                            Id = "c3710ece-665a-4446-be66-69231df238c5",
                            CategoryId = 2,
                            Description = "Banda resistencia",
                            Name = "Resistance Band",
                            Price = 13.99m,
                            Sku = "BAND046"
                        },
                        new
                        {
                            Id = "fc87091d-a009-4220-9e51-19fe90a397ab",
                            CategoryId = 1,
                            Description = "Soporte tablet",
                            Name = "Tablet Mount",
                            Price = 16.99m,
                            Sku = "MNT047"
                        },
                        new
                        {
                            Id = "37ace985-1e6c-4046-9da2-ac80fd72f119",
                            CategoryId = 2,
                            Description = "Bolsa agua",
                            Name = "Water Bag",
                            Price = 15.99m,
                            Sku = "H2O048"
                        },
                        new
                        {
                            Id = "b6c40a56-a274-42d4-b19e-213ce39b4168",
                            CategoryId = 1,
                            Description = "Hub cargador",
                            Name = "Charging Hub",
                            Price = 24.99m,
                            Sku = "CHRG049"
                        },
                        new
                        {
                            Id = "823554d1-7d56-415b-a2a3-6fffe92bbeb5",
                            CategoryId = 2,
                            Description = "Timer digital",
                            Name = "Sport Timer",
                            Price = 18.99m,
                            Sku = "TIME050"
                        });
                });

            modelBuilder.Entity("InventoryMan.Core.Entities.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electrónicos y accesorios tecnológicos"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Deportivos y fitness"
                        });
                });

            modelBuilder.Entity("InventoryMan.Core.Entities.Store", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Stores");

                    b.HasData(
                        new
                        {
                            Id = "e10fa0c7-aae4-4c51-95c8-1377f8d7be42",
                            Address = "Address 1",
                            Name = "Store 1",
                            Phone = "123456789"
                        },
                        new
                        {
                            Id = "fac7ead9-cda9-4e80-9289-47b67d915b2b",
                            Address = "Address 2",
                            Name = "Store 2",
                            Phone = "987654321"
                        });
                });

            modelBuilder.Entity("InventoryMan.Core.Entities.Inventory", b =>
                {
                    b.HasOne("InventoryMan.Core.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventoryMan.Core.Entities.Product", null)
                        .WithMany("Inventories")
                        .HasForeignKey("ProductId1");

                    b.HasOne("InventoryMan.Core.Entities.Store", "Store")
                        .WithMany("Inventories")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("InventoryMan.Core.Entities.Movement", b =>
                {
                    b.HasOne("InventoryMan.Core.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("InventoryMan.Core.Entities.Product", b =>
                {
                    b.HasOne("InventoryMan.Core.Entities.ProductCategory", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("InventoryMan.Core.Entities.Product", b =>
                {
                    b.Navigation("Inventories");
                });

            modelBuilder.Entity("InventoryMan.Core.Entities.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("InventoryMan.Core.Entities.Store", b =>
                {
                    b.Navigation("Inventories");
                });
#pragma warning restore 612, 618
        }
    }
}
