// <auto-generated />
using System;
using InventoryMan.Infrastructure.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InventoryMan.Infrastructure.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    partial class InventoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InventoryMan.Core.Entities.Inventory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("MinStock")
                        .HasColumnType("integer");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("StoreId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.HasIndex("ProductId", "StoreId")
                        .IsUnique();

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("InventoryMan.Core.Entities.Movement", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("SourceStoreId")
                        .HasColumnType("text");

                    b.Property<string>("TargetStoreId")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Movements");
                });

            modelBuilder.Entity("InventoryMan.Core.Entities.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = "ELEC-SMART-001",
                            CategoryId = 1,
                            Description = "Producto electrónico versátil",
                            Name = "Smartphone X1",
                            Price = 299.99m,
                            Sku = "SMRT001"
                        },
                        new
                        {
                            Id = "SPRT-WATCH-001",
                            CategoryId = 2,
                            Description = "Accesorio deportivo premium",
                            Name = "Reloj Deportivo Pro",
                            Price = 149.99m,
                            Sku = "SPRT002"
                        },
                        new
                        {
                            Id = "ELEC-AUDIO-001",
                            CategoryId = 1,
                            Description = "Audio de alta calidad",
                            Name = "Auriculares Wireless",
                            Price = 89.99m,
                            Sku = "AUDIO003"
                        },
                        new
                        {
                            Id = "SPRT-FITNS-001",
                            CategoryId = 2,
                            Description = "Equipo fitness resistente",
                            Name = "Pesas Ajustables",
                            Price = 199.99m,
                            Sku = "FIT004"
                        },
                        new
                        {
                            Id = "ELEC-TABL-001",
                            CategoryId = 1,
                            Description = "Tablet última generación",
                            Name = "Tablet Pro 10",
                            Price = 399.99m,
                            Sku = "TAB005"
                        },
                        new
                        {
                            Id = "SPRT-BALL-001",
                            CategoryId = 2,
                            Description = "Equipamiento deportivo",
                            Name = "Balón Profesional",
                            Price = 29.99m,
                            Sku = "BALL006"
                        },
                        new
                        {
                            Id = "ELEC-CAM-001",
                            CategoryId = 1,
                            Description = "Cámara compacta HD",
                            Name = "Cámara Digital X20",
                            Price = 249.99m,
                            Sku = "CAM007"
                        },
                        new
                        {
                            Id = "SPRT-WEAR-001",
                            CategoryId = 2,
                            Description = "Ropa deportiva premium",
                            Name = "Camiseta Tech-Fit",
                            Price = 34.99m,
                            Sku = "WEAR008"
                        },
                        new
                        {
                            Id = "ELEC-SPKR-001",
                            CategoryId = 1,
                            Description = "Altavoz potente",
                            Name = "Speaker Bluetooth",
                            Price = 79.99m,
                            Sku = "SPK009"
                        },
                        new
                        {
                            Id = "SPRT-SHOE-001",
                            CategoryId = 2,
                            Description = "Calzado deportivo",
                            Name = "Zapatillas Pro-Run",
                            Price = 89.99m,
                            Sku = "SHOE010"
                        },
                        new
                        {
                            Id = "ELEC-WATCH-001",
                            CategoryId = 1,
                            Description = "Smartwatch avanzado",
                            Name = "Reloj Smart V2",
                            Price = 199.99m,
                            Sku = "WATCH011"
                        },
                        new
                        {
                            Id = "SPRT-BAND-001",
                            CategoryId = 2,
                            Description = "Equipo de entrenamiento",
                            Name = "Banda Elástica Pro",
                            Price = 19.99m,
                            Sku = "BAND012"
                        },
                        new
                        {
                            Id = "ELEC-KEYB-001",
                            CategoryId = 1,
                            Description = "Teclado gaming",
                            Name = "Teclado RGB Pro",
                            Price = 129.99m,
                            Sku = "KEY013"
                        },
                        new
                        {
                            Id = "SPRT-YOGA-001",
                            CategoryId = 2,
                            Description = "Accesorio yoga",
                            Name = "Mat Premium",
                            Price = 39.99m,
                            Sku = "YOGA014"
                        },
                        new
                        {
                            Id = "ELEC-MOUS-001",
                            CategoryId = 1,
                            Description = "Mouse gaming",
                            Name = "Mouse Gamer X",
                            Price = 59.99m,
                            Sku = "MOUSE015"
                        },
                        new
                        {
                            Id = "SPRT-BOTL-001",
                            CategoryId = 2,
                            Description = "Botella deportiva",
                            Name = "Botella Térmica",
                            Price = 24.99m,
                            Sku = "BTL016"
                        },
                        new
                        {
                            Id = "ELEC-WCAM-001",
                            CategoryId = 1,
                            Description = "Webcam HD",
                            Name = "Webcam Pro 4K",
                            Price = 89.99m,
                            Sku = "CAM017"
                        },
                        new
                        {
                            Id = "SPRT-PACK-001",
                            CategoryId = 2,
                            Description = "Mochila deportiva",
                            Name = "Mochila Sport Pro",
                            Price = 44.99m,
                            Sku = "BAG018"
                        },
                        new
                        {
                            Id = "ELEC-POWR-001",
                            CategoryId = 1,
                            Description = "Batería portátil",
                            Name = "PowerBank 20000",
                            Price = 49.99m,
                            Sku = "PWR019"
                        },
                        new
                        {
                            Id = "SPRT-GLOV-001",
                            CategoryId = 2,
                            Description = "Guantes fitness",
                            Name = "Guantes Pro-Lift",
                            Price = 29.99m,
                            Sku = "GLV020"
                        },
                        new
                        {
                            Id = "ELEC-HUB-001",
                            CategoryId = 1,
                            Description = "Hub USB",
                            Name = "USB Hub 4-Port",
                            Price = 29.99m,
                            Sku = "USB021"
                        },
                        new
                        {
                            Id = "SPRT-TOWL-001",
                            CategoryId = 2,
                            Description = "Toalla deportiva",
                            Name = "Toalla Microfibra",
                            Price = 14.99m,
                            Sku = "TWL022"
                        },
                        new
                        {
                            Id = "ELEC-STND-001",
                            CategoryId = 1,
                            Description = "Soporte laptop",
                            Name = "Soporte Ergonómico",
                            Price = 39.99m,
                            Sku = "STND023"
                        },
                        new
                        {
                            Id = "SPRT-BAG-001",
                            CategoryId = 2,
                            Description = "Bolsa deporte",
                            Name = "Bolsa Gym Pro",
                            Price = 34.99m,
                            Sku = "GYM024"
                        },
                        new
                        {
                            Id = "ELEC-CABL-001",
                            CategoryId = 1,
                            Description = "Cable HDMI",
                            Name = "HDMI Premium 2m",
                            Price = 19.99m,
                            Sku = "HDMI025"
                        },
                        new
                        {
                            Id = "SPRT-HRTE-001",
                            CategoryId = 2,
                            Description = "Banda cardio",
                            Name = "Monitor Cardíaco",
                            Price = 49.99m,
                            Sku = "HRT026"
                        },
                        new
                        {
                            Id = "ELEC-CASE-001",
                            CategoryId = 1,
                            Description = "Funda tablet",
                            Name = "Funda Protectora",
                            Price = 24.99m,
                            Sku = "CASE027"
                        },
                        new
                        {
                            Id = "SPRT-KNEE-001",
                            CategoryId = 2,
                            Description = "Rodilleras pro",
                            Name = "Rodilleras Sport",
                            Price = 19.99m,
                            Sku = "KNEE028"
                        },
                        new
                        {
                            Id = "ELEC-WIFI-001",
                            CategoryId = 1,
                            Description = "Adaptador wifi",
                            Name = "WiFi Adapter Pro",
                            Price = 29.99m,
                            Sku = "WIFI029"
                        },
                        new
                        {
                            Id = "SPRT-ROPE-001",
                            CategoryId = 2,
                            Description = "Cuerda saltar",
                            Name = "Cuerda Pro-Jump",
                            Price = 14.99m,
                            Sku = "JUMP030"
                        },
                        new
                        {
                            Id = "ELEC-LED-001",
                            CategoryId = 1,
                            Description = "Luz LED USB",
                            Name = "LED Light Strip",
                            Price = 19.99m,
                            Sku = "LED031"
                        },
                        new
                        {
                            Id = "SPRT-HEAD-001",
                            CategoryId = 2,
                            Description = "Banda cabeza",
                            Name = "Banda Deportiva",
                            Price = 9.99m,
                            Sku = "HEAD032"
                        },
                        new
                        {
                            Id = "ELEC-SCRN-001",
                            CategoryId = 1,
                            Description = "Protector pantalla",
                            Name = "Screen Guard Pro",
                            Price = 14.99m,
                            Sku = "SCRN033"
                        },
                        new
                        {
                            Id = "SPRT-SHKR-001",
                            CategoryId = 2,
                            Description = "Botella shake",
                            Name = "Shaker Pro",
                            Price = 16.99m,
                            Sku = "SHAKE034"
                        },
                        new
                        {
                            Id = "ELEC-PHST-001",
                            CategoryId = 1,
                            Description = "Soporte móvil",
                            Name = "Phone Stand",
                            Price = 15.99m,
                            Sku = "STND035"
                        },
                        new
                        {
                            Id = "SPRT-WRST-001",
                            CategoryId = 2,
                            Description = "Muñequeras",
                            Name = "Wrist Support",
                            Price = 12.99m,
                            Sku = "WRST036"
                        },
                        new
                        {
                            Id = "ELEC-CLNR-001",
                            CategoryId = 1,
                            Description = "Limpiador pantalla",
                            Name = "Screen Cleaner",
                            Price = 9.99m,
                            Sku = "CLN037"
                        },
                        new
                        {
                            Id = "SPRT-SBAG-001",
                            CategoryId = 2,
                            Description = "Bolsa zapatos",
                            Name = "Shoe Bag Sport",
                            Price = 11.99m,
                            Sku = "BAG038"
                        },
                        new
                        {
                            Id = "ELEC-ORG-001",
                            CategoryId = 1,
                            Description = "Organizador cables",
                            Name = "Cable Manager",
                            Price = 8.99m,
                            Sku = "ORG039"
                        },
                        new
                        {
                            Id = "SPRT-MTOW-001",
                            CategoryId = 2,
                            Description = "Toalla pequeña",
                            Name = "Mini Towel",
                            Price = 7.99m,
                            Sku = "TWL040"
                        },
                        new
                        {
                            Id = "ELEC-PROT-001",
                            CategoryId = 1,
                            Description = "Protector cable",
                            Name = "Cable Protector",
                            Price = 6.99m,
                            Sku = "PROT041"
                        },
                        new
                        {
                            Id = "SPRT-MEAS-001",
                            CategoryId = 2,
                            Description = "Banda medición",
                            Name = "Measure Tape",
                            Price = 8.99m,
                            Sku = "MEAS042"
                        },
                        new
                        {
                            Id = "ELEC-FAN-001",
                            CategoryId = 1,
                            Description = "Mini ventilador",
                            Name = "USB Fan",
                            Price = 12.99m,
                            Sku = "FAN043"
                        },
                        new
                        {
                            Id = "SPRT-LOCK-001",
                            CategoryId = 2,
                            Description = "Candado gym",
                            Name = "Gym Lock",
                            Price = 9.99m,
                            Sku = "LOCK044"
                        },
                        new
                        {
                            Id = "ELEC-PAD-001",
                            CategoryId = 1,
                            Description = "Almohadilla mouse",
                            Name = "Mouse Pad Pro",
                            Price = 11.99m,
                            Sku = "PAD045"
                        },
                        new
                        {
                            Id = "SPRT-RBAN-001",
                            CategoryId = 2,
                            Description = "Banda resistencia",
                            Name = "Resistance Band",
                            Price = 13.99m,
                            Sku = "BAND046"
                        },
                        new
                        {
                            Id = "ELEC-MNT-001",
                            CategoryId = 1,
                            Description = "Soporte tablet",
                            Name = "Tablet Mount",
                            Price = 16.99m,
                            Sku = "MNT047"
                        },
                        new
                        {
                            Id = "SPRT-H2O-001",
                            CategoryId = 2,
                            Description = "Bolsa agua",
                            Name = "Water Bag",
                            Price = 15.99m,
                            Sku = "H2O048"
                        },
                        new
                        {
                            Id = "ELEC-CHRG-001",
                            CategoryId = 1,
                            Description = "Hub cargador",
                            Name = "Charging Hub",
                            Price = 24.99m,
                            Sku = "CHRG049"
                        },
                        new
                        {
                            Id = "SPRT-TIME-001",
                            CategoryId = 2,
                            Description = "Timer digital",
                            Name = "Sport Timer",
                            Price = 19.99m,
                            Sku = "TIME050"
                        });
                });

            modelBuilder.Entity("InventoryMan.Core.Entities.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electrónicos y accesorios tecnológicos"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Deportivos y fitness"
                        });
                });

            modelBuilder.Entity("InventoryMan.Core.Entities.Store", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Stores");

                    b.HasData(
                        new
                        {
                            Id = "STR-01",
                            Address = "Address 1",
                            Name = "Store 1",
                            Phone = "123456789"
                        },
                        new
                        {
                            Id = "STR-02",
                            Address = "Address 2",
                            Name = "Store 2",
                            Phone = "987654321"
                        },
                        new
                        {
                            Id = "STR-03",
                            Address = "Address 3",
                            Name = "Store 3",
                            Phone = "985632147"
                        });
                });

            modelBuilder.Entity("InventoryMan.Core.Entities.Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Test");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Data = "Database connection successfully established"
                        });
                });

            modelBuilder.Entity("InventoryMan.Core.Entities.Inventory", b =>
                {
                    b.HasOne("InventoryMan.Core.Entities.Product", "Product")
                        .WithMany("Inventories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventoryMan.Core.Entities.Store", "Store")
                        .WithMany("Inventories")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("InventoryMan.Core.Entities.Movement", b =>
                {
                    b.HasOne("InventoryMan.Core.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("InventoryMan.Core.Entities.Product", b =>
                {
                    b.HasOne("InventoryMan.Core.Entities.ProductCategory", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("InventoryMan.Core.Entities.Product", b =>
                {
                    b.Navigation("Inventories");
                });

            modelBuilder.Entity("InventoryMan.Core.Entities.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("InventoryMan.Core.Entities.Store", b =>
                {
                    b.Navigation("Inventories");
                });
#pragma warning restore 612, 618
        }
    }
}
